### ISSUE TITLE
Don't receive the email popup after installing

### ISSUE THREAD

**Issue by dylanmazurek** [watchedsyncforkodi/service.watchedsync#5]
I've installed your add-on on 2 of my Sony TV's and I am unable to connect them to the service as I don't receive the popup with the email address.

**Comment by watchedsyncforkodi** [comment]
We need some debug logs to help further. The easiest method is to use the logfile uploader:

Instructions to install the logfile uploader is at https://kodi.wiki/view/Add-on:Kodi_Logfile_Uploader

Please can you then run the following test for me:
1) Turn on debug mode (see https://kodi.wiki/view/Log_file/Easy) on the 2 kodi devices
2) Reboot both devices
3) After Kodi loads the menu on both devices, wait 5 mins with Kodi idle sitting at the home menu. Do not start any updates or playback any movies or tv shows.
4) Upload the debug log from both devices and share the URL with me. It is really important both devices are in debug mode (there is normally text displayed in the top left corner of the screen when in debug mode) otherwise I won't be able to help.
5) Turn off debug mode

With the debug logs I may be able to spot something

**Comment by watchedsyncforkodi** [comment]
Someone else reported a similar problem and it turned out to be the Kodi skin they were using. They temporarily set the Kodi skin back to default and the popup appeared
